### ISSUE TITLE
Gitsense doesnt turn on for any private repo hosted in GitLab 

### ISSUE THREAD

**Issue by saravanadel** [gitsense/insight#16]
Gitsense doesnt switch on for any private repo. I am using GitLab which is hosted internally (in port 80) . Oauth seems to work fine , but when i turn on GitSense i get this error.  

Cloning error
An error occurred while trying to clone this repository for indexing

i cant seem to find the reason why. 

Gitsense is hosted in 443 and i tried re-configuring Gitlab in 443 and still the same issue.

**Comment by gitsense** [comment]
@saravanadel Are you able to connect to private repos on https://gitlab.com?

A major update to GitSense is underway, which should significantly improve how you can interact with merge/pull requests, so we'll only be able to provide limited support for the current GitSense version.

What are the errors that you see in the GitSense admin tool?  To see the failed clone requests, login to the admin panel and click on the "table icon" for the "Add Git" repo process.

![snip_20170911213040](https://user-images.githubusercontent.com/5347894/30308200-8d326d2e-9738-11e7-9916-91ffd9b29afd.png)

From there, you can click on the request number to view the clone log.

**Comment by saravanadel** [comment]
Thanks for the prompt reply. Looks like the project URLs point to localhost which is something that i did not configure correctly in GitLab. I am going to check and see if this solve this issue.

**Comment by saravanadel** [comment]
Its working. thanks.

**Comment by gitsense** [comment]
Great.  Was this error an oversight or could some documentations be improved?

**Comment by saravanadel** [comment]
The documentation on the 'Add git repo' link to find the errors, could have helped or even if it can be mentioned on the error dialog to tell the user where they can find the info, could help. I did not go through the full video, but i should say the steps was pretty well recorded. i was searching for a troubleshooting section or FAQ's, and certainly this can be added there . 

my only other thought is, what if gitsense was configured for non-ssl and gitlab was ssl, would this work ?

**Comment by gitsense** [comment]
> my only other thought is, what if gitsense was configured for non-ssl and gitlab was ssl, would this work ?

This should work provided GitSense is used in standalone mode.  If you want to use the Chrome extension, this won't work due to the mix security settings.   However, at the present moment, SSL must be enable for GitSense to be supported.
