### ISSUE TITLE
Can't make the gitsense work with Azure DevOps

### ISSUE THREAD

**Issue by rokam** [gitsense/insight#21]
I've already registered the application, and copied the configurations, although when I try to OAuth a do receive the following message:
`400: {"Error":"invalid_client","ErrorDescription":"Failed to deserialize the JsonWebToken object."}`

When I get the code param value, I'm able to decode the jwt at https://www.jsonwebtoken.io/

What should I put at Base URL field?

**Comment by gitsense** [comment]
Sorry.  GitSense for Azure is no longer supported and it's kind of embarrassing but we can't seem to find the credentials to remove our listing.
